server {
    listen $PORT;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://nigeria-bids-backend-wmyc45oroq-bq.a.run.app/;
        proxy_set_header Host nigeria-bids-backend-wmyc45oroq-bq.a.run.app;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
